rabbitmq:
  queue: test-queue

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  application:
    name: whatsapp
  main:
    allow-bean-definition-overriding: true